config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
    
    unauthenticated do
      root 'splash#index', as: :unauthenticated_root
    end
  end  

  resources :groups, only: [:index, :new, :create, :show, :destroy] do
    resources :expenses, only: [:index, :new, :create, :show, :destroy]
  end

  root "splash#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    user ||= User.new # if the user is a guest
    can :read, :all
    if user.admin?
      can :manage, :all
    else
      can :manage, Group, user_id: user.id
      can :manage, Expense, user_id: user.id
      can :read, :all
      can :read, :all
    end
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  # associations
  has_many :group_expenses, dependent: :destroy
  has_many :groups, through: :group_expenses
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  # validations
  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_float: true, greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  # associations
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  # validations
  validates :name, presence: true, length: { in: 1..25 }
  validates :icon, presence: true
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # associations
  has_many :groups, class_name: 'Group', dependent: :destroy, foreign_key: 'user_id'
  has_many :expenses, class_name: 'Expense', dependent: :destroy, foreign_key: 'user_id'

  # validations
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :find_group

  def new
    @expense = Expense.new
  end

  def create
    unless @group.user == current_user
      return redirect_to groups_path, notice: 'You can only create expenses from your categories'
    end

    if expense_params[:group_ids].length == 1
      return redirect_to new_group_expense_path(@group), alert: 'Must select at least one category'
    end

    @expense = Expense.new(expense_params)
    @expense.user = current_user

    if @expense.save
      flash[:notice] = 'Expense created successfully'
      redirect_to @group
    else
      flash[:alert] = @expense.errors.full_messages.first if @expense.errors.any?
      render :new, status: :unprocessable_entity
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: [])
  end

  def find_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_user

  def index
    @groups = @user.groups.all
  end

  def new
    @group = Group.new
  end

  def create
    puts group_params.inspect
    @group = Group.new(group_params)
    @group.user = @user
    if @group.save
      redirect_to groups_path, notice: 'Category added successfully'
    else
      flash.now[:alert] = @group.errors.full_messages.first if @group.errors.any?
      render :new, status: 400
    end
  end

  def show
    @group = Group.find(params[:id])
    redirect_to groups_path, notice: 'You are not authorized to access this page!' unless @group.user == @user
    @expenses = @group.expenses.order(created_at: :desc)
    @total = @expenses.sum(:amount)
  end

  private

  def set_user
    @user = current_user
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon_tag(icon_name)
    content_tag(:i, '', class: "fas fa-#{icon_name}")
  end
end

app/views/expenses/new.html.erb
<div class="header">
    <%= link_to "←", group_path(@group.id), class:"arrow-back" %>
    <h2 class="groups-title">Add a New Transaction</h2>
</div>

<div class="form-container">
  <%= form_with model: @expense, url: group_expenses_path, local: true do |f| %>
    <%= f.text_field :name, autofocus: true, placeholder: "Name", class: "form-control log" %>
    <%= f.number_field :amount, autofocus: true, placeholder: "Amount", class: "form-control log" %>
    <div class="checkbox-btn">
      <%= f.label :group_ids, "Select one or more categories:", class: "label-text" %>
      <div class="checkboxes">
        <%= f.collection_check_boxes :group_ids, current_user.groups, :id, :name do |b| %>
          <div class="form-control">
            <%= b.check_box %>
            <%= b.label%>
          </div>
        <% end %>
      </div>

      <div class="fixed-button">
        <div class="save-div link-to">
            <%= f.submit "Save", class: "save-button-des" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %> 
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="groups-header">
    <h2 class="groups-title">Snapbudget</h2>
</div>


<div class="categories">
  <% if @groups.empty? %>
  <div class="get-started">
    <h3 class="started">Get Started</h3>
    <span class="div">Add your first budget by clicking on the button below</span>
  </div>
  <% else %>

  <div class="categories-container">
    <% @groups.each do |group| %>
      <div class="category-card">
        <div class="category-icon">
          <%= image_tag group.icon, alt: 'icon', class: "icon" %>
        </div>
        <div class="card-text">
          <div class="top-card">
            <%= link_to group_path(group.id.to_s), style: "text-decoration: none;" do %>
              <p class="category-name"><%= group.name %></p>
            <% end %>
            <p class="amount">$<%= group.expenses.sum(:amount) %></p>
          </div>
          <div class="bottom-card">
            <p class="date"><%= group.created_at.strftime('%d %B, %Y') %></p>
            <p class="user">by <%= current_user.name %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="fixed-button">
    <div class="link-to">
      <%= link_to 'Add New Category'.html_safe, new_group_path, class: "butt btn-success button-link" %>
    </div>
  </div>

  </div>
</div>

app/views/groups/new.html.erb
<div class="header">
    <%= link_to "←", root_path, class:"arrow-back" %>
    <h2 class="groups-title">Add New Category</h2>
</div>

<div class="form-container">
<%= form_with model: @group, url: groups_path, local: true do |f| %>
  <%= f.text_field :name, autofocus: true, placeholder: "Category Name", class:"form-control log" %>
  
  <div class="form-group">
    <%= f.collection_select(:icon, [
        ['cash.png', 'Investment 💵'],
        ['hospital.png', 'Health 🏥'],
        ['shopping.png', 'Shopping 🛍️'],
        ['sports.png', 'Sports ⚽'],
        ['popcorn.png', 'Movies 🍿'],
        ['travel.png', 'Travel ✈️'],
        ['more.png', 'Others 📓']
      ], :first, :last, { prompt: 'Select Icon' }, { class: 'form-control log' }) %>
  </div>
  <div class="fixed-button">
    <div class="save-div link-to">
      <%= f.submit "Save", class:"save-button-des"%>
    </div>
  </div>
<% end %>
</div>

app/views/groups/show.html.erb
<div class="header">
    <%= link_to "←", groups_path, class:"arrow-back" %>
    <h2 class="groups-title">Transactions</h2>
</div>

<div class="transactions-container">
  <div class="transactions-title">
    <p class="parr"><%= @group.name %></p>
    <p class="parr">Total: $<%= @group.expenses.sum(:amount) %></p>
  </div>

  <% @expenses.each do |expense| %>
    <div class="transaction-card">
      <div class="category-icon">
        <%= image_tag @group.icon, alt: 'icon', class: "icon" %>
      </div>
      <div class="card-text">
        <div class="name-amount">
          <h4><%= expense.name %></h4>
          <p class="amount">$<%= expense.amount %></p>
        </div>
        <p class="date"><%= expense.created_at.strftime('%d %B, %Y') %></p>
      </div>
    </div>
  <% end %>

  <div class="fixed-button">
    <%= link_to new_group_expense_path(group_id: @group.id) do %>
      <button class="btn btn-success but">Add new transaction</button>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
  </head>

  <body>
    <p class="alert alert-primary notice"><%= notice %></p>
    <p class="alert alert-primary alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-primary">
  <%= link_to "←", :back, class: "nav-link" %>
  <%= link_to 'Pennywise', groups_path,  class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Categories', groups_path,  class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Category', new_group_path,  class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-light' %> 
      </li>
    </ul>
  </div>
</nav>

app/views/splash/index.html.erb
<div class="splash-container">
  <div class="logo-container">
    <h1 class="app-title">snapbudget</h1>
    <h3 class="subtitle">Manage your expenses collectively</h3>
    <p class="sub-sub">Please create an account or log in</p>
  </div>
  <div class="sign-links">
    <%= link_to 'Get started', new_user_registration_path,  class: 'btn btn-primary sign-up' %> 
    <%= link_to 'Log in'.html_safe, new_user_session_path, class: 'log-in' %>
  </div>
</div>
<div class="shadow"></div>